### ISSUE TITLE
Sidebar links refer to the actual file path

### ISSUE THREAD

**Issue by peggycupcake** [reportunit/reportunit#1]
The links between the sidebar and the ones in the main Index page do not link to the same thing. 

When I put the dashboards on a webserver, the index page links work but all the ones in the sidebar point to file:///* which then the webserver cannot find.

**Comment by anshooarora** [comment]
If you pass absolute paths, they will be retained.  I would recommend using relative paths instead:

```
\\ all reports will be created in the target/current folder
\\ this will retain all paths as long as they are in the same folder
reportunit . 

\\ relative to different input and output folders
reportunit ".\xml-reports" ".\html-reports"
```

If you see the samples (http://relevantcodes.com/Tools/ReportUnit/Index.html) and analyze the sidebar links, you will see that I've used approach 1 above.

**Comment by peggycupcake** [comment]
Ok I got it working properly when I run:
```
reportunit .
```
The sidebar links still refer to "file:///test/*.html" and the index main page links refer to the html file when I run:
```
reportunit test
test is a folder in the current directory.
```
