### ISSUE TITLE
Which licence is it?

### ISSUE THREAD

**Issue by jon-p** [reportunit/reportunit#19]
It would make using ReportUnit much simpler in a corporate environment if you could state which licence it is e.g. MIT, BSD, etc
Thanks.

**Comment by anshooarora** [comment]
MIT.

I will make it more obvious on the website too, thanks for pointing it out.

**Comment by jon-p** [comment]
Great - thanks very much Anshoo. 


     On Friday, 30 October 2015, 21:52, Anshoo Arora <notifications@github.com> wrote:
   
 

 MIT.I will make it more obvious on the website too, thanks for pointing it out.—
