### ISSUE TITLE
Feature - View Errors/Failed/Passed/Incnclusive Reports by using direct URL

### ISSUE THREAD

**Issue by arasu-rrk** [reportunit/reportunit#2]
Can you please add support for viewing Errors/Failed/Passed/Incnclusive Reports by using direct URL?

Like this...

http://relevantcodes.com/Tools/ReportUnit/Gallio.html?filterTests=Failed

**Comment by anshooarora** [comment]
I will try to add this feature to the next release.  You will be able to filter tests and suites based on URL parameters.

**Comment by anshooarora** [comment]
In the upcoming version (should be here later this or early next week), you will be able to filter directly using URLs:

```
<url>?passedTests
<url>?failedTests
<url>?errorTests
<url>?inconclusiveTests
<url>?skippedTests
<url>?passedSuites
<url>?failedSuites
<url>?errorSuites
<url>?inconclusiveSuites
<url>?skippedSuites
```

**Comment by arasu-rrk** [comment]
@anshooarora Thanks... :+1:
