### ISSUE TITLE
Different HTML reports from same xml file

### ISSUE THREAD

**Issue by canb00** [reportunit/reportunit#24]
Hi,
We are using ReportUnit.exe file to create our reports. We have a strange bug. If we execute Reportunit.exe via my local machine manually, I can generate a proper HTML report. But if I execute this *.exe file in my Jenkins server(Windows SQLServer 2012) after test runs, I got another HTML report.

I used the same xml file in both machine.
The one in the jenkins server doesnt contain any info about test runs.  There are many empty divs.
You may see the difference among the HTML file. I am using version 1.2

![diff](https://cloud.githubusercontent.com/assets/16006443/11380587/aa196882-92ff-11e5-9bb8-ab5ac103a425.PNG)
![diff-2](https://cloud.githubusercontent.com/assets/16006443/11380588/aa1d3642-92ff-11e5-8381-bb309bbddc44.PNG)

**Comment by anshooarora** [comment]
Hmm its hard to say what's happening between the 2 boxes.  Will you be able to pull from repo and debug?

**Comment by canb00** [comment]
We pulled from repo and rebuild the app. Right now, everything works fine.
But the executable in the download section nehaves strangely.

Thanks you
