### ISSUE TITLE
Add a release, a zip file, to download?

### ISSUE THREAD

**Issue by lboening** [reportunit/reportunit#32]
Is there a chance a release could be created? It comes in handy for local deployment.

**Comment by anshooarora** [comment]
I will upload the latest executable to the [website](http://reportunit.relevantcodes.com/) and Nuget tomorrow with the recent updates. Does that answer your query?

**Comment by anshooarora** [comment]
The package is now available on the <a href='http://reportunit.relevantcodes.com'>website</a> and also on Nuget.

**Comment by lboening** [comment]
Thank you! I found it.
