### ISSUE TITLE
Output argument not working properly

### ISSUE THREAD

**Issue by azmelanar** [reportunit/reportunit#39]
For generate report I use next command:

    packages\ReportUnit.1.5.0-alpha3a\tools\ReportUnit.exe reports/TestResult.xml reports/index.html

But it does not create `reports/index.html`, only `reports/TestResult.html`

**Comment by anshooarora** [comment]
For a single report, index.html will not be created.  Index.html contains data for multiple suites and since a single file is passed, a summary page isn't required.
