### ISSUE TITLE
while using reportunit 1.5 the  report page become unresponsive [A transparent shield wrap the whole page] after clicking inside the div which displays the details of failure.

### ISSUE THREAD

**Issue by eliteofindia** [reportunit/reportunit#54]

**Comment by eliteofindia** [comment]
![image](https://cloud.githubusercontent.com/assets/17291142/13803646/47ec7494-eb81-11e5-8b56-e1438998fa3f.png)

**Comment by anshooarora** [comment]
What browser are you using? Can you share a sample report?

**Comment by eliteofindia** [comment]
The attached zip file has 2 reports you can try with any one of them.
open the failure details block as marked in above attached snapshot and click inside that div then you will be able to replicate.

[Index.zip](https://github.com/reportunit/reportunit/files/177547/Index.zip)

**Comment by eliteofindia** [comment]
Any updates about the issue [anshoo](https://github.com/anshooarora)?

**Comment by anshooarora** [comment]
I tested but unable to see the same behavior.

Clicking error message:
![1](https://cloud.githubusercontent.com/assets/4107384/13952174/f664f4e4-f002-11e5-9cbb-39036f5835a0.png)

Clicking elsewhere on the screen
![2](https://cloud.githubusercontent.com/assets/4107384/13952173/f6629596-f002-11e5-816c-242273658815.png)

**Comment by eliteofindia** [comment]
I described issue as clicking inside div which displays the details about failure.
Please refer to my attached image above to get the exact div where you should click.

**Comment by eliteofindia** [comment]
issue still exist but i am closing the streak here.
