### ISSUE TITLE
Issue: Dark layout appeared when click inside opened status message modal

### ISSUE THREAD

**Issue by andrei-turavets-epam** [reportunit/reportunit#59]
Hi,
I haven't found the same issue in github. so post the new one
I used lates 1.5 reportUnit with Nunit 3 with log output.
Steps to reproduce.
1. Run the test which has some text output.
2. For this test in test report generated by reportunit click on icon in column "StatusMessage".
Here we see the modal with our log output.
3. Now click inside opened modal window. Expected: nothing happened, actual: The dar overlay appeared across all the browser window and you cannot proceed with report interactions, only refresh window can help.

One note: possibly it can be related to this issue https://github.com/Dogfalo/materialize/issues/1647
as when i click inside status message window new div with id="materialize-lean-overlay-1", id="materialize-lean-overlay-2" appeares

**Comment by andrei-turavets-epam** [comment]
looks like it duplicates 
https://github.com/reportunit/reportunit/issues/54
But it was closed although the problem still exists

**Comment by h5necom** [comment]
Also cannot scroll the logs at the moment at all and have to refresh the page to get out of the "dark view"
