### ISSUE TITLE
Application is not working

### ISSUE THREAD

**Issue by anurajsl** [reportunit/reportunit#7]
Hi Anshoo,

I have tried using your application, but for me it's not working at all. The actual problem is that i dont know how to use it. What I will do withthat exe file ? How should I run those commands. Can u please explain these details please. It would be of so helpful then.

**Comment by anshooarora** [comment]
You can either run the exe file via command prompt or you can drag/drop your folders/test-result files.

All commands to be executed from the command line are given here:  http://reportunit.relevantcodes.com/

So you just have to pass the path of the input and output file/folders from your test runner (nunit, mstest or gallio) and the report will be generated.

**Comment by anshooarora** [comment]
Andrey and I discussed this issue just now,  he sent me the file and I was able to test with it.  It didn't work because your version of NUnit has the following test-suite node:

```
<test-suite name="ArticleBetaTest" executed="True" success="False" time="113.204" asserts="0">
```

What's strange is, there is no <code>result</code> attribute, which is why its failing.  Is there anyway you can update your version from 2.5.1 to one of the newer versions?

**Comment by anurajsl** [comment]
But I am using 2.6.4 version of NUnit.

**Comment by anshooarora** [comment]
If you can share the test result XML file,  I will be able to see what's causing the issue.

**Comment by Andrey-Bushman** [comment]
Is this history with the `result` attribute finished? Whether the reason of absenting that attribute was found?

**Comment by anurajsl** [comment]
I have updated Nunit to the latest version and the issue was resolved. Many thanks to Andrew-Bushman and Anshoo for their help.

**Comment by anshooarora** [comment]
Closing issue as the issue solved after upgrading to latest version.
