### ISSUE TITLE
nunit categories not shown in report

### ISSUE THREAD

**Issue by Austin-Chadwick** [reportunit/reportunit#95]
Hi,

I am trying out your tool reportunit with nunit and I can't seem to get the categories to show in the reports even though categories are part of the xml output from nunit. Please see the attached xml output and resulting html. 

[GitHub issue.zip](https://github.com/reportunit/reportunit/files/774796/GitHub.issue.zip)

How come categories like this in the xml do not show in the report so that I can filter by them?

                <categories>
                  <category name="Release0.1" />
                  <category name="Sprint000" />
                  <category name="BasicNavigation" />
                  <category name="UserInterface" />
                </categories>

Is there something I am doing wrong?

Thanks so much for the tool and the help!

Austin

**Comment by Austin-Chadwick** [comment]
@anshooarora, 

I know this is an open source free project so all is pretty much a huge gift to begin with and I very thankful for that. 

For my planning though I would like to know if this is something you plan to work on soon or I should try to come up with a solution to my problem solely on my own. 

Either way I am good but I would just like to know for planning if possible. 

Thanks!

Austin

**Comment by rudra7** [comment]
Hi Austin,

I just tried your file with latest report unit and categories are getting displayed. PFA
[Release0.1_Sprint000_AcceptanceTests.dll.seqat01sim.testresults.zip](https://github.com/reportunit/reportunit/files/828497/Release0.1_Sprint000_AcceptanceTests.dll.seqat01sim.testresults.zip)

**Comment by Austin-Chadwick** [comment]
@rudra7, 
Thanks so much for investigating and responding!

It looks like I need to try with the same version you are (i.e. the latest). Are you using 1.5-beta-1? For whatever version you are using, how can I access it? The link (http://relevantcodes.com/wp-content/plugins/download-monitor/download.php?id=23) to 1.5-beta-1 at http://relevantcodes.com/reportunit/ is broken. 

I suppose I could pull from GitHub and build locally if I had to but is there an easier way to get the latest?

Thanks!

@Austin-Chadwick

cc:
@anshooarora

**Comment by rudra7** [comment]
@Austin-Chadwick 

I can share my build but building locally won't take much time of yours. Let me know if you need any help. 

Close this issue if it works fine.

Regards,
Rudra

**Comment by Austin-Chadwick** [comment]
@rudra7.

It works! Thanks!

@Austin-Chadwick

cc:
@anshooarora
